---
parameters:
    env(OPEN_ID_DISCOVERY_URL): ''
    env(OPEN_ID_HOSTED_DOMAIN): ''
    env(OPEN_ID_CLIENT_ID): ''
    env(OPEN_ID_CLIENT_SECRET): ''
    env(DEEPL_API_KEY): ''
roadiz_rozier:
    translate_assistant:
        deepl_api_key: '%env(string:DEEPL_API_KEY)%'
    csv_encoder_options:
        csv_delimiter: ';'
    open_id:
        # Verify User info in JWT at each login
        verify_user_info: false
        # Standard OpenID autodiscovery URL, required to enable OpenId login in Roadiz CMS.
        discovery_url: '%env(string:OPEN_ID_DISCOVERY_URL)%'
        # For public identity providers (such as Google), restrict users emails by their domain.
        hosted_domain: '%env(string:OPEN_ID_HOSTED_DOMAIN)%'
        # OpenID identity provider OAuth2 client ID
        oauth_client_id: '%env(string:OPEN_ID_CLIENT_ID)%'
        # OpenID identity provider OAuth2 client secret
        oauth_client_secret: '%env(string:OPEN_ID_CLIENT_SECRET)%'
        scopes:
            - openid
            - profile
            - email
        requires_local_user: true
        force_ssl_on_redirect_uri: false
        # Only when local users are not required, creating virtual users
        # with following roles.
        granted_roles:
            - ROLE_USER
            - ROLE_BACKEND_USER
            - ROLE_SUPERADMIN

    bookmarks:
        - label: 'Documentation'
          url: 'https://docs.roadiz.io/'
        - label: 'Github'
          url: 'https://github.com/roadiz'
        - label: '%env(string:APP_EXAMPLE_BOOKMARK_LABEL)%'
          url: '%env(string:APP_EXAMPLE_BOOKMARK_URL)%'

    entries:
        dashboard:
            name: dashboard
            route: adminHomePage
            icon: rz-icon-ri--dashboard-line

        nodes:
            name: nodes
            route: ~
            icon: rz-icon-ri--command-line
            roles: [ 'ROLE_ACCESS_NODES' ]
            subentries:
                all_nodes:
                    name: 'all.nodes'
                    route: nodesHomePage
                    icon: rz-icon-rz--status-container-line
                    roles: ~
                draft_nodes:
                    name: 'draft.nodes'
                    route: nodesHomeDraftPage
                    icon: rz-icon-rz--status-draft-line
                    roles: ~
                pending_nodes:
                    name: 'pending.nodes'
                    route: nodesHomePendingPage
                    icon: rz-icon-rz--status-pending-line
                    roles: ~
                archived_nodes:
                    name: 'archived.nodes'
                    route: nodesHomeArchivedPage
                    icon: rz-icon-rz--status-archived-line
                    roles: ~
                deleted_nodes:
                    name: 'deleted.nodes'
                    route: nodesHomeDeletedPage
                    icon: rz-icon-rz--status-deleted-line
                    roles: ~
                shadow_nodes:
                    name: 'shadow.nodes'
                    route: nodesHomeShadowPage
                    icon: rz-icon-rz--status-shadow-container-line
                    roles: ~
                search_nodes:
                    name: 'search.nodes'
                    route: searchNodePage
                    icon: rz-icon-ri--search-line
                    roles: ~

        manage_documents:
            name: 'manage.documents'
            route: ~
            icon: rz-icon-ri--image-line
            roles: [ 'ROLE_ACCESS_DOCUMENTS' ]
            subentries:
                all_documents:
                    name: 'all.documents'
                    route: documentsHomePage
                    icon: rz-icon-ri--image-line
                    roles: [ 'ROLE_ACCESS_DOCUMENTS' ]
                private_documents:
                    name: 'private_documents'
                    route: documentsPrivateHomePage
                    icon: rz-icon-ri--lock-2-line
                    roles: [ 'ROLE_ACCESS_DOCUMENTS' ]
                unused_documents:
                    name: 'unused_documents'
                    route: documentsUnusedPage
                    icon: rz-icon-ri--close-line
                    roles: [ 'ROLE_ACCESS_DOCUMENTS' ]
                duplicated_documents:
                    name: 'duplicated_documents'
                    route: documentsDuplicatesPage
                    icon: rz-icon-ri--file-copy-line
                    roles: [ 'ROLE_ACCESS_DOCUMENTS' ]

        manage_tags:
            name: 'manage.tags'
            route: tagsHomePage
            icon: 'rz-icon-ri--price-tag-3-line'
            roles: [ 'ROLE_ACCESS_TAGS' ]

        construction:
            name: 'construction'
            route: ~
            icon: 'rz-icon-ri--hammer-line'
            roles:
                - 'ROLE_ACCESS_NODETYPES'
                - 'ROLE_ACCESS_ATTRIBUTES'
                - 'ROLE_ACCESS_TRANSLATIONS'
                - 'ROLE_ACCESS_REDIRECTIONS'
                - 'ROLE_ACCESS_WEBHOOKS'
                - 'ROLE_ACCESS_REALMS'
            subentries:
                manage_nodeTypes:
                    name: 'manage.nodeTypes'
                    route: nodeTypesHomePage
                    icon: 'rz-icon-ri--kanban-view'
                    roles: ['ROLE_ACCESS_NODETYPES']
                manage_attributes:
                    name: 'manage.attributes'
                    route: attributesHomePage
                    icon: 'rz-icon-ri--server-line'
                    roles: ['ROLE_ACCESS_ATTRIBUTES']
                manage_translations:
                    name: 'manage.translations'
                    route: translationsHomePage
                    icon: 'rz-icon-ri--translate'
                    roles: ['ROLE_ACCESS_TRANSLATIONS']
                manage_redirections:
                    name: 'manage.redirections'
                    route: redirectionsHomePage
                    icon: 'rz-icon-ri--compass-3-line'
                    roles: ['ROLE_ACCESS_REDIRECTIONS']
                manage_webhooks:
                    name: 'manage.webhooks'
                    route: webhooksHomePage
                    icon: 'rz-icon-ri--space-ship-line'
                    roles: ['ROLE_ACCESS_WEBHOOKS']
                manage_realms:
                    name: 'manage.realms'
                    route: realmsHomePage
                    icon: 'rz-icon-ri--spy-line'
                    roles: ['ROLE_ACCESS_REALMS']

        user_system:
            name: 'user.system'
            route: ~
            icon: 'rz-icon-ri--user-line'
            roles: ['ROLE_ACCESS_USERS', 'ROLE_ACCESS_GROUPS']
            subentries:
                manage_users:
                    name: 'manage.users'
                    route: usersHomePage
                    icon: 'rz-icon-ri--user-line'
                    roles: ['ROLE_ACCESS_USERS']
                manage_groups:
                    name: 'manage.groups'
                    route: groupsHomePage
                    icon: rz-icon-ri--group-line
                    roles: ['ROLE_ACCESS_GROUPS']

        manage_customForms:
            name: 'manage.customForms'
            route: customFormsHomePage
            icon: 'rz-icon-ri--questionnaire-line'
            roles: [ 'ROLE_ACCESS_CUSTOMFORMS' ]


        settings:
            name: 'settings'
            route: ~
            icon: rz-icon-ri--settings-line
            roles: ['ROLE_ACCESS_SETTINGS']
            subentries:
                all_settings:
                    name: 'all.settings'
                    route: settingsHomePage
                    icon: rz-icon-ri--settings-4-line
                    roles: ['ROLE_ACCESS_SETTINGS']
                setting_groups_dynamic:
                    # This is a special menu entry replaced by all settings groups
                    name: 'setting.groups.dynamic' # do not rename this
                    icon: rz-icon-ri--settings-4-line
                    roles: ['ROLE_ACCESS_SETTINGS']
                setting_groups:
                    name: 'setting.groups'
                    route: settingGroupsHomePage
                    icon: rz-icon-ri--equalizer-3-line
                    roles: ['ROLE_ACCESS_SETTINGS']

